services:
  db:
    image: postgres:17.0
    container_name: db_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./api:/rails
    ports:
      - 3001:3001
    depends_on:
      - redis
      - db

  sidekiq:
    container_name: sidekiq_container
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - ./api/.env
    volumes:
      - ./api:/rails
    depends_on:
      - app
      - redis

  redis:
    container_name: redis_container
    image: redis:7.0
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    depends_on:
      - db


volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
