/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        name?: string;
                        profile_text?: string;
                        /** Format: binary */
                        avatar?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        target_user_id: number;
                    };
                };
            };
            responses: {
                /** @description フォロー成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/followings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー解除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"] & {
                            is_followed_by_me: boolean;
                        };
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/follow_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FollowStats"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserList"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserList"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google OAuth認証コールバック
         * @description Googleから取得した認証コードを使ってユーザー認証を行う。
         *     既存ユーザーの場合はアクセストークンを返し、新規ユーザーの場合は暗号化されたメールアドレスを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Googleから取得した認証コード */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description 認証成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoogleAuthResponse"];
                    };
                };
                /** @description 認証コードがない */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description トークン交換失敗、ユーザー情報取得失敗、またはAuthRequest保存失敗 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/line/login_url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LINE OAuth認証URL取得
         * @description LINE OAuth認証用のログインURLを取得する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログインURL作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LineLoginUrlResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/line/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LINE OAuth認証コールバック
         * @description LINEから取得した認証コードを使ってユーザー認証を行う。
         *     既存ユーザーの場合はアクセストークンを返し、新規ユーザーの場合は暗号化されたメールアドレスを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description LINEから取得した認証コード */
                        code: string;
                        /** @description CSRF対策用のstateパラメータ */
                        state: string;
                        /** @description 暗号化されたLineLoginレコードID */
                        line_login_id: string;
                    };
                };
            };
            responses: {
                /** @description 認証成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LineAuthResponse"];
                    };
                };
                /** @description stateパラメータが無効、または認証コードがない */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
                /** @description トークン交換失敗、IDトークン検証失敗、またはAuthRequest保存失敗 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    first?: number;
                    after?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WhatToDiscardProblemList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 何切る問題を作成
         * @description 新しい何切る問題を作成する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        round?: string | null;
                        turn?: number | null;
                        wind?: string | null;
                        points?: number | null;
                        description?: string | null;
                        dora_id: number;
                        hand1_id: number;
                        hand2_id: number;
                        hand3_id: number;
                        hand4_id: number;
                        hand5_id: number;
                        hand6_id: number;
                        hand7_id: number;
                        hand8_id: number;
                        hand9_id: number;
                        hand10_id: number;
                        hand11_id: number;
                        hand12_id: number;
                        hand13_id: number;
                        tsumo_id: number;
                    };
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WhatToDiscardProblem"];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 何切る問題を取得
         * @description 指定したIDの何切る問題を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WhatToDiscardProblem"];
                    };
                };
                /** @description 問題が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * 何切る問題を更新
         * @description 自分が作成した何切る問題を更新する
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        round?: string | null;
                        turn?: number | null;
                        wind?: string | null;
                        points?: number | null;
                        description?: string | null;
                        dora_id: number;
                        hand1_id: number;
                        hand2_id: number;
                        hand3_id: number;
                        hand4_id: number;
                        hand5_id: number;
                        hand6_id: number;
                        hand7_id: number;
                        hand8_id: number;
                        hand9_id: number;
                        hand10_id: number;
                        hand11_id: number;
                        hand12_id: number;
                        hand13_id: number;
                        tsumo_id: number;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WhatToDiscardProblem"];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 問題が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 何切る問題を削除
         * @description 自分が作成した何切る問題を削除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems/{what_to_discard_problem_id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 何切る問題にいいねする
         * @description 指定した何切る問題にいいねを追加する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    what_to_discard_problem_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description いいね作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Like"];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 問題が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 既にいいね済み */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems/{what_to_discard_problem_id}/likes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 何切る問題のいいねを取り消す
         * @description 指定した何切る問題のいいねを削除する
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    what_to_discard_problem_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description いいね削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 問題またはいいねが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems/{what_to_discard_problem_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 何切る問題のコメント一覧を取得
         * @description 指定した何切る問題の親コメント一覧を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    what_to_discard_problem_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description コメント一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentList"];
                    };
                };
                /** @description 問題が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 何切る問題にコメントする
         * @description 指定した何切る問題にコメントを追加する
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    what_to_discard_problem_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        comment: {
                            content: string;
                            parent_comment_id?: number | null;
                        };
                    };
                };
            };
            responses: {
                /** @description コメント作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
                /** @description 認証エラー */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 問題が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/what_to_discard_problems/{what_to_discard_problem_id}/comments/{comment_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * コメントの返信一覧を取得
         * @description 指定したコメントの返信（子コメント）一覧を取得する
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    what_to_discard_problem_id: number;
                    comment_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 返信一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentList"];
                    };
                };
                /** @description コメントが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Comment: {
            id: number;
            content: string;
            parent_comment_id: number | null;
            replies_count: number;
            commentable_type: string;
            commentable_id: number;
            /** Format: date-time */
            created_at: string;
            user: components["schemas"]["User"];
        };
        CommentList: {
            comments: components["schemas"]["Comment"][];
        };
        Like: {
            id: number;
            user_id: number;
            likable_id: number;
            likable_type: string;
            /** Format: date-time */
            created_at: string;
        };
        User: {
            id: number;
            name: string;
            avatar_url: string | null;
            profile_text: string | null;
        };
        FollowStats: {
            following_count: number;
            followers_count: number;
        };
        UserList: {
            users: components["schemas"]["User"][];
        };
        Error: {
            /** @description エラーメッセージ */
            error: string;
        };
        Errors: {
            errors: string[];
        };
        GoogleAuthResponse: {
            /** @description ユーザー名（既存ユーザーの場合） */
            user_name: string | null;
            /** @description JWTアクセストークン（既存ユーザーの場合） */
            access_token: string | null;
            /** @description JWTリフレッシュトークン（既存ユーザーの場合） */
            refresh_token: string | null;
            /** @description 暗号化されたメールアドレス（新規ユーザーの場合） */
            encrypted_email: string | null;
        };
        LineLoginUrlResponse: {
            /** @description LINE OAuth認証URL */
            login_url: string;
            /** @description 暗号化されたLineLoginレコードID */
            line_login_id: string;
        };
        LineAuthResponse: {
            /** @description ユーザー名（既存ユーザーの場合） */
            user_name: string | null;
            /** @description JWTアクセストークン（既存ユーザーの場合） */
            access_token: string | null;
            /** @description JWTリフレッシュトークン（既存ユーザーの場合） */
            refresh_token: string | null;
            /** @description 暗号化されたメールアドレス（新規ユーザーの場合） */
            encrypted_email: string | null;
        };
        Session: {
            /** @description ログイン状態 */
            is_logged_in: boolean;
            /** @description ユーザーID */
            user_id?: number | null;
        };
        WhatToDiscardProblem: {
            id: number;
            hand1_id: number;
            hand2_id: number;
            hand3_id: number;
            hand4_id: number;
            hand5_id: number;
            hand6_id: number;
            hand7_id: number;
            hand8_id: number;
            hand9_id: number;
            hand10_id: number;
            hand11_id: number;
            hand12_id: number;
            hand13_id: number;
            tsumo_id: number;
            dora_id: number;
            round?: string | null;
            turn?: number | null;
            wind?: string | null;
            points?: number | null;
            description?: string | null;
            comments_count: number;
            likes_count: number;
            votes_count: number;
            my_like_id: number | null;
            my_vote_tile_id: number | null;
            user: components["schemas"]["User"];
            /** Format: date-time */
            created_at: string;
        };
        PageInfo: {
            has_next_page: boolean;
            has_previous_page: boolean;
            start_cursor?: number | null;
            end_cursor?: number | null;
        };
        WhatToDiscardProblemList: {
            problems: components["schemas"]["WhatToDiscardProblem"][];
            page_info: components["schemas"]["PageInfo"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
